// Regenerates src/styles/kanji-fonts.css: @font-face rules for only the
// Shippori Mincho subset files that hold the kanji and kana this UI prints
// itself. Bundling the whole Japanese font would add ~10 MB of files to the
// binary for a couple of dozen glyphs; text the model writes falls back to
// the system's Japanese fonts instead.
//
// Run after changing any kanji in the UI:  node scripts/kanji-fonts.mjs
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const weights = [800];

// Every non-ASCII glyph in the source, so nothing printed is missed.
const glyphs = new Set();
function scan(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) scan(path);
    else if (/\.(tsx?|css)$/.test(entry.name) && !entry.name.endsWith('kanji-fonts.css')) {
      for (const ch of readFileSync(path, 'utf8')) {
        const cp = ch.codePointAt(0);
        // CJK symbols, kana and ideographs only.
        if ((cp >= 0x3000 && cp <= 0x30ff) || (cp >= 0x4e00 && cp <= 0x9fff)) glyphs.add(cp);
      }
    }
  }
}
scan(join(root, 'src'));

function parseRange(range) {
  return range.split(',').map((part) => {
    const [lo, hi] = part.trim().replace(/^U\+/i, '').split('-');
    return [parseInt(lo, 16), parseInt(hi ?? lo, 16)];
  });
}

let out = `/* Generated by scripts/kanji-fonts.mjs. Do not edit; rerun it instead. */\n`;
for (const weight of weights) {
  const css = readFileSync(join(root, `node_modules/@fontsource/shippori-mincho/${weight}.css`), 'utf8');
  for (const block of css.match(/@font-face\s*{[^}]*}/g) ?? []) {
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1];
    const file = /url\(\.\/files\/([^)]+\.woff2)\)/.exec(block)?.[1];
    if (!range || !file) continue;
    const ranges = parseRange(range);
    const needed = [...glyphs].filter((cp) => ranges.some(([lo, hi]) => cp >= lo && cp <= hi));
    if (needed.length === 0) continue;
    out += `@font-face {
  font-family: 'Shippori Mincho';
  font-style: normal;
  font-display: swap;
  font-weight: ${weight};
  src: url('@fontsource/shippori-mincho/files/${file}') format('woff2');
  unicode-range: ${range};
}
`;
  }
}
writeFileSync(join(root, 'src/styles/kanji-fonts.css'), out);
console.log(`${glyphs.size} glyphs → ${(out.match(/@font-face/g) ?? []).length} subset files`);
